version: "3.7"
services:
  frontend:
    container_name: sample
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
#    environment:
#      - CHOKIDAR_USEPOLLING=true
    volumes:
      - '/app/node_modules'
      - '.:/app'
    ports:
      - 3000:3000

# docker-compose up